apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - selector:
        dnsZones:
        {{- range $zone := .Values.hostedZones }}
          - {{ $zone }}
        {{- end }}
      dns01:
        route53:
          region: us-west-2
          accessKeyID: {{ .Values.accessKeyID }}
          secretAccessKeySecretRef:
            name: letsencrypt-dns-route53-credentials
            key: secretAccessKey
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-dns-route53-credentials
type: Opaque
data:
  accessKeyID: {{ .Values.accessKeyID | b64enc }}
  secretAccessKey: {{ .Values.secretAccessKey | b64enc }}
